mutation createActivity($input: CreateActivityInput!) {
  createActivity(input: $input)
}

mutation updateActivity($input: UpdateBannerInput!) {
  updateActivity(input: $input)
}

mutation deleteActivity($input: DeleteActivityInput!) {
  deleteActivity(input: $input)
}

mutation sortActivity($input: SortActivityInput!) {
  sortActivity(input: $input)
}
