query articleEntry($id: Int!) {
  articleEntry(id: $id) {
    id
    article {
      id
      title
      imageUrl
      merchant {
        id
        name
      }
    }
  }
}
query articlreEntries($params: ArticleEntryParams) {
  articlreEntries(params: $params) {
    total
    items {
      id
      article {
        id
        title
        imageUrl
        merchant {
          id
          name
        }
      }
    }
  }
}
