mutation createBanner($input: CreateBannerInput!) {
  createBanner(input: $input)
}

mutation updateBanner($input: UpdateBannerInput!) {
  updateBanner(input: $input)
}

mutation deleteBanner($input: DeleteBannerInput!) {
  deleteBanner(input: $input)
}

mutation sortBanner($input: SortBannerInput!) {
  sortBanner(input: $input)
}

mutation changeBannerStatus($input: ChangeBannerStatusInput!) {
  changeBannerStatus(input: $input)
}
